# Generated by Django 6.0.1 on 2026-05-21 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_householdsupplyrequest_scheduleperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='householdsupplyrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'заявка на хоз.нужды', 'verbose_name_plural': 'заявки на хоз.нужды'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'смена', 'verbose_name_plural': 'смены'},
        ),
        migrations.AlterModelOptions(
            name='scheduleperiod',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'период графика', 'verbose_name_plural': 'периоды графика'},
        ),
        migrations.AlterField(
            model_name='householdsupplyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='householdsupplyrequest',
            name='item_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Позиция 1'),
        ),
        migrations.AlterField(
            model_name='householdsupplyrequest',
            name='item_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Позиция 2'),
        ),
        migrations.AlterField(
            model_name='householdsupplyrequest',
            name='item_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Позиция 3'),
        ),
        migrations.AlterField(
            model_name='householdsupplyrequest',
            name='item_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Позиция 4'),
        ),
        migrations.AlterField(
            model_name='householdsupplyrequest',
            name='item_5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Позиция 5'),
        ),
        migrations.AlterField(
            model_name='householdsupplyrequest',
            name='pvz_address',
            field=models.CharField(max_length=255, verbose_name='ПВЗ'),
        ),
        migrations.AlterField(
            model_name='householdsupplyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_requests', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pvz_address',
            field=models.CharField(max_length=255, verbose_name='ПВЗ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shifts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Смены'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='scheduleperiod',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Разрешено ли сотрудникам проставлять смены', verbose_name='Открыт для сотрудников'),
        ),
        migrations.AlterField(
            model_name='scheduleperiod',
            name='month',
            field=models.PositiveSmallIntegerField(verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='scheduleperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='scheduleperiod',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_period_updates', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='scheduleperiod',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год'),
        ),
    ]
