# Generated by Django 6.0.3 on 2026-06-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_householdsupplyrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
