# Generated by Django 6.0.1 on 2026-05-21 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'обратная связь', 'verbose_name_plural': 'обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='siteannouncement',
            options={'ordering': ['-created_at'], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-announcement__created_at'], 'verbose_name': 'уведомление', 'verbose_name_plural': 'уведомления'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/', verbose_name='Вложение (фото)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('bug', 'Баг'), ('wish', 'Пожелания'), ('question', 'Вопрос'), ('other', 'Другое')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('reviewed', 'Просмотрено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='siteannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='siteannouncement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='siteannouncement',
            name='message',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='siteannouncement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.siteannouncement', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
