# Generated by Django 6.0.1 on 2026-04-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingquestion_alter_trainingmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininganswer',
            name='correct_sequence',
            field=models.PositiveSmallIntegerField(default=0, help_text='Для типа «ordering»: правильный порядок шага (1…n). Для остальных — 0.'),
        ),
        migrations.AddField(
            model_name='trainingattempt',
            name='breakdown',
            field=models.JSONField(blank=True, default=list, help_text='По вопросам: ok, тип, как ответил стажёр (для администратора).'),
        ),
        migrations.AddField(
            model_name='trainingattempt',
            name='responses',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trainingquestion',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Для order_judgment: statements, sequence_valid, correct_order (список номеров шагов).'),
        ),
        migrations.AddField(
            model_name='trainingquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один ответ'), ('multiple', 'Несколько ответов'), ('ordering', 'Установить порядок'), ('order_judgment', 'Проверка порядка (верно/неверно)')], default='single', max_length=32),
        ),
        migrations.AddField(
            model_name='trainingtest',
            name='pass_threshold_percent',
            field=models.PositiveIntegerField(default=90, help_text='Минимальный процент верных ответов для успешной сдачи (например, 90).'),
        ),
        migrations.AddField(
            model_name='trainingtest',
            name='require_all_other_materials_completed',
            field=models.BooleanField(default=False, help_text='Если включено: тест доступен только после завершения всех остальных материалов.'),
        ),
        migrations.AddField(
            model_name='trainingtest',
            name='reset_all_training_progress_on_fail',
            field=models.BooleanField(default=False, help_text='При неуспешной попытке удалить весь прогресс обучения пользователя (кроме самой попытки).'),
        ),
        migrations.AlterField(
            model_name='traininganswer',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
