# Generated by Django 6.0.1 on 2026-05-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_extended_test_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmaterial',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='training/pdfs/'),
        ),
    ]
