# Generated by Django 6.0.1 on 2026-05-21 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingmaterial_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininganswer',
            options={'verbose_name': 'вариант ответа', 'verbose_name_plural': 'варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='trainingattempt',
            options={'ordering': ('-created_at',), 'verbose_name': 'попытка теста', 'verbose_name_plural': 'попытки тестов'},
        ),
        migrations.AlterModelOptions(
            name='trainingmaterial',
            options={'ordering': ('module_title', 'order', 'id'), 'verbose_name': 'учебный материал', 'verbose_name_plural': 'учебные материалы'},
        ),
        migrations.AlterModelOptions(
            name='trainingprogress',
            options={'verbose_name': 'прогресс обучения', 'verbose_name_plural': 'прогресс обучения'},
        ),
        migrations.AlterModelOptions(
            name='trainingquestion',
            options={'ordering': ('order', 'id'), 'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='trainingslide',
            options={'ordering': ('order', 'id'), 'verbose_name': 'слайд', 'verbose_name_plural': 'слайды'},
        ),
        migrations.AlterModelOptions(
            name='trainingtest',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.AlterField(
            model_name='traininganswer',
            name='correct_sequence',
            field=models.PositiveSmallIntegerField(default=0, help_text='Для типа «ordering»: правильный порядок шага (1…n). Для остальных — 0.', verbose_name='Порядок (для sorting)'),
        ),
        migrations.AlterField(
            model_name='traininganswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Верный'),
        ),
        migrations.AlterField(
            model_name='traininganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='training.trainingquestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='traininganswer',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='trainingattempt',
            name='breakdown',
            field=models.JSONField(blank=True, default=list, help_text='По вопросам: ok, тип, как ответил стажёр (для администратора).', verbose_name='Разбор по вопросам'),
        ),
        migrations.AlterField(
            model_name='trainingattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата попытки'),
        ),
        migrations.AlterField(
            model_name='trainingattempt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='trainingattempt',
            name='max_score',
            field=models.PositiveIntegerField(verbose_name='Максимум баллов'),
        ),
        migrations.AlterField(
            model_name='trainingattempt',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Сдан'),
        ),
        migrations.AlterField(
            model_name='trainingattempt',
            name='responses',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='trainingattempt',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='trainingattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание (текст)'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='module_title',
            field=models.CharField(default='Как работать с программой WB PVZ', help_text='Группа материалов (например, название курса)', max_length=255, verbose_name='Модуль / курс'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='training/pdfs/', verbose_name='PDF-файл'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='completed_slides',
            field=models.PositiveIntegerField(default=0, verbose_name='Пройдено слайдов'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='total_slides',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего слайдов'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Для order_judgment: statements, sequence_valid, correct_order (список номеров шагов).', verbose_name='Доп. данные (JSON)'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Один ответ'), ('multiple', 'Несколько ответов'), ('ordering', 'Установить порядок'), ('order_judgment', 'Проверка порядка (верно/неверно)')], default='single', max_length=32, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.trainingtest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='trainingquestion',
            name='text',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='trainingslide',
            name='image_url',
            field=models.CharField(blank=True, help_text='URL картинки (обычно из /static/)', max_length=500, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='trainingslide',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='training.trainingmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='trainingslide',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='trainingslide',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст слайда'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='training.trainingmaterial', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='pass_threshold_percent',
            field=models.PositiveIntegerField(default=90, help_text='Минимальный процент верных ответов для успешной сдачи (например, 90).', verbose_name='Порог сдачи (%)'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='require_all_other_materials_completed',
            field=models.BooleanField(default=False, help_text='Если включено: тест доступен только после завершения всех остальных материалов в каталоге (кроме материала с этим тестом).', verbose_name='Сначала пройти все материалы'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='reset_all_training_progress_on_fail',
            field=models.BooleanField(default=False, help_text='При неуспешной попытке удалить весь прогресс обучения пользователя (кроме самой попытки).', verbose_name='Сбросить прогресс при провале'),
        ),
        migrations.AlterField(
            model_name='trainingtest',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название теста'),
        ),
    ]
