# Generated by Django 6.0.1 on 2026-05-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_credentials',
            field=models.BooleanField(default=False),
        ),
    ]
