# Generated by Django 6.0.1 on 2026-05-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_intern',
            field=models.BooleanField(default=True, verbose_name='Стажёр'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_credentials',
            field=models.BooleanField(default=False, verbose_name='Требуется смена пароля при входе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pvz_address',
            field=models.CharField(max_length=255, verbose_name='Адрес ПВЗ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('intern', 'Стажёр'), ('staff_manager', 'Штатный менеджер'), ('chief_manager', 'Главный менеджер'), ('administrator', 'Администратор'), ('owner', 'Владелец')], default='intern', max_length=20, verbose_name='Роль'),
        ),
    ]
